version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/react-app
      - /react-app/node_modules
    environment:
      - WATCHPACK_POLLING=true
