function PrivacyData() {
  const privacyData = {
    introduction: {
      lable: 'Introduction',
      description: [
        `Welcome to MetalMaker3D (“Company”, “we”, “our”, “us”)!`,
        ` These Terms
            of Service (“Terms”, “Terms of Service”) govern your use of our website located at
            metalmaker3d.com (together or individually “Service”) operated by MetalMaker3D.`,
        `  Our Privacy Policy also governs your use of our Service and explains how we
            collect, safeguard and disclose information that results from your use of our web
            pages.`,
        ` Your agreement with us includes these Terms and our Privacy Policy
            (“Agreements”). You acknowledge that you have read and understood Agreements, and
            agree to be bound of them.`,
        `If you do not agree with (or cannot comply with) Agreements, then you may not use
            the Service, but please let us know by emailing at support@metalmaker3d.com so we
            can try to find a solution. These Terms apply to all visitors, users and others
            who wish to access or use Service.`,
      ],
    },
    definitions: {
      lable: 'Definitions',
      description: [
        `SERVICE means the metalmaker3d.com website operated by MetalMaker3D.`,
        `PERSONAL DATA means data about a living individual who can be identified from
        those data (or from those and other information either in our possession or likely
        to come into our possession).`,
        ` USAGE DATA is data collected automatically either generated by the use of Service
        or from Service infrastructure itself (for example, the duration of a page visit).`,
        `COOKIES are small files stored on your device (computer or mobile device).`,
        ` DATA CONTROLLER means a natural or legal person who (either alone or jointly or in
          common with other persons) determines the purposes for which and the manner in
          which any personal data are, or are to be, processed. For the purpose of this
          Privacy Policy, we are a Data Controller of your data.`,
        `DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who
          processes the data on behalf of the Data Controller. We may use the services of
          various Service Providers in order to process your data more effectively.`,
        `DATA SUBJECT is any living individual who is the subject of Personal Data.`,
        `THE USER is the individual using our Service. The User corresponds to the Data
          Subject, who is the subject of Personal Data.`,
      ],
    },
    informationCollection: {
      lable: 'Information Collection and Use',
      description: [
        `We collect several different types of information for various purposes to provide
      and improve our Service to you.`,
      ],
    },
    typesOfDataCollected: {
      lable: 'Types of Data Collected',
      description: [
        `Personal Data`,
        `While using our Service, we may ask you to provide us with certain personally
        identifiable information that can be used to contact or identify you (“Personal
        Data”). Personally identifiable information may include, but is not limited to:`,
        `0.1. Email address`,
        `0.2. First name and last name`,
        `0.3. Phone number`,
        `0.4. Address, Country, State, Province, ZIP/Postal code, City`,
        `0.5. Cookies and Usage Data`,
        `We may use your Personal Data to contact you with newsletters, marketing or
        promotional materials and other information that may be of interest to you. You
        may opt out of receiving any, or all, of these communications from us by following
        the unsubscribe link.`,
      ],
    },
    usageData: {
      lable: 'Usage Data',
      description: [
        `We may also collect information that your browser sends whenever you visit our
      Service or when you access Service by or through any device (“Usage Data”).`,
        `This Usage Data may include information such as your computer’s Internet Protocol
    address (e.g. IP address), browser type, browser version, the pages of our Service
    that you visit, the time and date of your visit, the time spent on those pages,
    unique device identifiers and other diagnostic data.~`,
        ` When you access Service with a device, this Usage Data may include information
    such as the type of device you use, your device unique ID, the IP address of your
    device, your device operating system, the type of Internet browser you use, unique
    device identifiers and other diagnostic data.`,
        `Location Data`,
        `We may use and store information about your location if you give us permission to
    do so (“Location Data”). We use this data to provide features of our Service, to
    improve and customize our Service.`,
        `You can enable or disable location services when you use our Service at any time
    by way of your device settings.`,
        `Tracking Cookies Data`,
        `We use cookies and similar tracking technologies to track the activity on our
    Service and we hold certain information.`,
        `Cookies are files with a small amount of data which may include an anonymous
    unique identifier. Cookies are sent to your browser from a website and stored on
    your device. Other tracking technologies are also used such as beacons, tags and
    scripts to collect and track information and to improve and analyze our Service.`,
        `You can instruct your browser to refuse all cookies or to indicate when a cookie
    is being sent. However, if you do not accept cookies, you may not be able to use
    some portions of our Service.`,
        `Examples of Cookies we use:`,
        `0.1. Session Cookies: We use Session Cookies to operate our Service.`,
        `0.2. Preference Cookies: We use Preference Cookies to remember your preferences
    and various settings.`,
        `0.3. Security Cookies: We use Security Cookies for security purposes.`,
        `0.4. Advertising Cookies: Advertising Cookies are used to serve you with
    advertisements that may be relevant to you and your interests.`,
        `Other Data`,
        ` While using our Service, we may also collect the following information: sex, age,
    date of birth, place of birth, passport details, citizenship, registration at
    place of residence and actual address, telephone number (work, mobile), details of
    documents on education, qualification, professional training, employment
    agreements, NDA agreements, information on bonuses and compensation, information
    on marital status, family members, social security (or other taxpayer
    identification) number, office location and other data.`,
      ],
    },
  };
  return privacyData;
}

export default PrivacyData;
